# Generated by Django 4.1.5 on 2023-01-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
    ]
