# Generated by Django 4.1.5 on 2023-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.DateField(verbose_name='Дата истечения срока использования'),
        ),
    ]
