# Generated by Django 4.1.5 on 2023-01-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_name_product_title_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
    ]
