# Generated by Django 4.1.5 on 2023-01-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_payment_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения срока использования'),
        ),
        migrations.AlterField(
            model_name='product',
            name='produced_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Производитель'),
        ),
    ]
