# Generated by Django 4.1.5 on 2023-01-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_order_amount_order_total_price_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
