# Generated by Django 4.1.5 on 2023-01-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
