# Generated by Django 4.1.5 on 2023-01-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0002_remove_order_payment_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='owner',
        ),
    ]
