# Generated by Django 4.1.5 on 2023-01-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oder', '0003_rename_user_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='activation_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
